define([], function() {
    return {
        "TaxonomyPickerSuggestedTerms": "Termini/parole suggeriti",
        "TaxonomyPickerNoTerm": "Nessun termine/parola trovato",
        "TaxonomyPickerTermLocationPrefix": "In",
        "saveButtonLabel": "Registrare",
        "cancelButtonLabel": "Annullare",
        "selectTermLabel": "Seleziona un termine...",
        "PeoplePickerSuggestion": "Suggerimenti",
        "PeoplePickerNoResults": "Nessun risultato.",
        "PeoplePickerLoading": "Caricamento in corso…",
        "EmptyPeoplePicker": "Selezionate un utilizzatore.",
        "takePicture": "Take a picture",
        "startVideo": "Begin capture",
        "stopVideo": "Stop capture",
        "removeButtonLabel": "Cancellare",
        "NoMediaMessage": "Non c'é nessun media(foto/video) da visualizzare",
        "NavHomeText": "Andare alla pagina iniziale",
        "FullscreenLabel": "Passare in modalità  schermo intero",
        "AbortFullScreenLabel": "Uscire dalla  modalità  schermo intero",
        "ElementTypeColumnLabel": "Tipo di elemento",
        "OperationColumnLabel": "Operazione",
        "AddLabel": "Aggiunta",
        "UpdateLabel": "Aggiornamento",
        "DeleteLabel": "Cancellazione",
        "UploadLabel": "Caricare",
        "titleLabel": "Titolo",
        "IdColumnLabel": "ID",
        "PendingTransactionsLabel": "Operazione in attesa di sincronizzazione",
        "TransactionErrorsLabel": "Errori di sincronizzazione",
        "NoTransactionsLabel": "Nessuna operazione in corso",
        "NoSyncErrorsLabel": "Nessun errore durante l'ultima sincronizzazione",
        "clearSyncErrors": "Svuotare la lista degli errori",
        "download": "Scaricare"
    }
});