define([], function() {
    return {
        "TaxonomyPickerSuggestedTerms": "Warunki sugerowane",
        "ItemPickerSuggestedTerms": "elementy Sugerowane",
        "TaxonomyPickerNoTerm": "Nie znaleziono warunku",
        "ItemPickerNoTerm": "Nie znaleziono elementu",
        "TaxonomyPickerTermLocationPrefix": "W",
        "saveButtonLabel": "Zapisz",
        "cancelButtonLabel": "Anuluj",
        "selectTermLabel": "Wybierz termin...",
        "PeoplePickerSuggestion": "Propozycja",
        "PeoplePickerNoResults": "Brak wyników.",
        "PeoplePickerLoading": "Ładowanie…",
        "EmptyPeoplePicker": "Proszę wybrać użytkownika",
        "takePicture": "Zrób zdjęcie",
        "startVideo": "Rozpocznij zapis",
        "stopVideo": "Zakończ zapis",
        "removeButtonLabel": "Usuń",
        "NoMediaMessage": "Brak mediów do wyświetlenia",
        "NavHomeText": "Powrót na stronę główną",
        "FullscreenLabel": "Przełącz na pełny ekran",
        "AbortFullScreenLabel": "Wyjdź z trybu pełnoekranowego",
        "ElementTypeColumnLabel": "Typ elementu",
        "OperationColumnLabel": "Operacja",
        "AddLabel": "Dodać",
        "UpdateLabel": "Zaktualizować",
        "DeleteLabel": "Usunąć",
        "UploadLabel": "Ładowanie",
        "titleLabel": "Tytuł",
        "IdColumnLabel": "ID",
        "PendingTransactionsLabel": "Operacje oczekujące na synchronizację",
        "TransactionErrorsLabel": "Błąd synchronizacji",
        "NoTransactionsLabel": "Brak operacji w toku",
        "NoSyncErrorsLabel": "Brak błędu podczas ostatniej synchronizacji",
        "clearSyncErrors": "Wyszyść listę",
        "download": "Pobierz"
    }
});