define([], function() {
    return {
        "TaxonomyPickerSuggestedTerms": "建议的术语",
        "TaxonomyPickerNoTerm": "找不到术语",
        "TaxonomyPickerTermLocationPrefix": "在…",
        "saveButtonLabel": "保存",
        "cancelButtonLabel": "取消",
        "selectTermLabel": "选择一个词...",
        "PeoplePickerSuggestion": "建议",
        "PeoplePickerNoResults": "无结果",
        "PeoplePickerLoading": "加载中",
        "EmptyPeoplePicker": "请选择用户",
        "takePicture": "选择图片",
        "startVideo": "开始拍摄",
        "stopVideo": "停止拍摄",
        "removeButtonLabel": "清除",
        "NoMediaMessage": "无播放内容",
        "NavHomeText": "返回主页",
        "FullscreenLabel": "切换到全屏",
        "AbortFullScreenLabel": "退出全屏",
        "ElementTypeColumnLabel": "项目类型",
        "OperationColumnLabel": "操作",
        "AddLabel": "添加",
        "UpdateLabel": "更新",
        "DeleteLabel": "删除",
        "UploadLabel": "加载",
        "titleLabel": "标题",
        "IdColumnLabel": "ID",
        "PendingTransactionsLabel": "操作等待同步",
        "TransactionErrorsLabel": "同步错误",
        "NoTransactionsLabel": "无待处理的事务",
        "NoSyncErrorsLabel": "无同步错误",
        "clearSyncErrors": "清空列表",
        "download": "下载"
    }
});