// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'container': string;
  'dropdownContainer': string;
}
const cssExports: CssExports;
export default cssExports;
