define([], function() {
    return {
        "TaxonomyPickerSuggestedTerms": "Términos sugeridos",
        "TaxonomyPickerNoTerm": "Ningún termino encontrado",
        "TaxonomyPickerTermLocationPrefix": "En",
        "saveButtonLabel": "Guardar",
        "cancelButtonLabel": "Anular",
        "selectTermLabel": "Selecciona un término...",
        "PeoplePickerSuggestion": "Sugerencias",
        "PeoplePickerNoResults": "Ningún resultado",
        "PeoplePickerLoading": "Cargando ….",
        "EmptyPeoplePicker": "Por favor, seleccione un usuario",
        "takePicture": "Take a picture",
        "startVideo": "Begin capture",
        "stopVideo": "Stop capture",
        "removeButtonLabel": "Suprimir",
        "NoMediaMessage": "Ninguna foto ó vídeo que mostrar",
        "NavHomeText": "Ir a la página de inicio",
        "FullscreenLabel": "Pasar a pantalla completa",
        "AbortFullScreenLabel": "Salir de pantalla completa",
        "ElementTypeColumnLabel": "Tipo de elemento",
        "OperationColumnLabel": "Operación",
        "AddLabel": "Añadir",
        "UpdateLabel": "Actualización",
        "DeleteLabel": "Supresión",
        "UploadLabel": "Cargar",
        "titleLabel": "Título",
        "IdColumnLabel": "ID",
        "PendingTransactionsLabel": "Operaciones en espera de sincronización",
        "TransactionErrorsLabel": "Error de sincronización",
        "NoTransactionsLabel": "Ninguna transacción en curso",
        "NoSyncErrorsLabel": "Ningún error durante la última sincronización",
        "clearSyncErrors": "Vaciar la lista de errores"
    }
});