define([], function() {
    return {
        "TaxonomyPickerSuggestedTerms": "Termes suggérés",
        "TaxonomyPickerNoTerm": "Aucun terme trouvé",
        "TaxonomyPickerTermLocationPrefix": "Dans ",
        "saveButtonLabel": "Enregistrer",
        "cancelButtonLabel": "Annuler",
        "selectTermLabel": "Sélectionner un terme...",
        "PeoplePickerSuggestion": "Suggestions",
        "PeoplePickerNoResults": "Aucun résultat.",
        "PeoplePickerLoading": "Chargement…",
        "EmptyPeoplePicker": "Veuillez séléctionné un utilisateur.",
        "takePicture": "Prendre photo",
        "startVideo": "Commencer l'enregistrement",
        "stopVideo": "Terminer l'enregistrement",
        "removeButtonLabel": "Supprimer",
        "NoMediaMessage": "Il n'y a aucun média à afficher",
        "NavHomeText": "Aller à la page d'accueil",
        "FullscreenLabel": "Basculer en mode plein écran",
        "AbortFullScreenLabel": "Quitter le mode plein écran",
        "ElementTypeColumnLabel": "Type d'élément",
        "OperationColumnLabel": "Opération",
        "AddLabel": "Ajout",
        "UpdateLabel": "Mise à jour",
        "DeleteLabel": "Suppression",
        "UploadLabel": "Charger",
        "titleLabel": "Titre",
        "IdColumnLabel": "ID",
        "PendingTransactionsLabel": "Transactions en attente de synchronisation",
        "TransactionErrorsLabel": "Erreurs de synchronisation",
        "NoTransactionsLabel": "Aucune transaction en cours",
        "NoSyncErrorsLabel": "Aucune erreur lors de la dernère synchronisation",
        "clearSyncErrors": "Vider la liste"
    }
});