define([], function() {
    return {
        "TaxonomyPickerSuggestedTerms": "Termos sugeridos",
        "TaxonomyPickerNoTerm": "Nenhum termo encontrado",
        "TaxonomyPickerTermLocationPrefix": "Em",
        "saveButtonLabel": "Salvar",
        "cancelButtonLabel": "Anular",
        "selectTermLabel": "Selecione um termo...",
        "PeoplePickerSuggestion": "Sugestões",
        "PeoplePickerNoResults": "Nenhum resultado",
        "PeoplePickerLoading": "Carregando…",
        "EmptyPeoplePicker": "Por favor, selecionar um usuário",
        "takePicture": "Tirar a foto",
        "startVideo": "Começar a gravar o vídeo",
        "stopVideo": "Terminar de gravar o vídeo",
        "removeButtonLabel": "Apagar",
        "NoMediaMessage": "Não há fotos ou vídeos para mostrar",
        "NavHomeText": "Voltar à página principal",
        "FullscreenLabel": "Passar ao modo tela inteira",
        "AbortFullScreenLabel": "Sair do modo tela inteira",
        "ElementTypeColumnLabel": "Tipo de elemento",
        "OperationColumnLabel": "Operação",
        "AddLabel": "Adicionar",
        "UpdateLabel": "Atualização",
        "DeleteLabel": "Supressão",
        "UploadLabel": "Carregar",
        "titleLabel": "Título",
        "IdColumnLabel": "ID",
        "PendingTransactionsLabel": "Operações esperando sincronização",
        "TransactionErrorsLabel": "Erro de sincronização",
        "NoTransactionsLabel": "Nenhuma transação em espera",
        "NoSyncErrorsLabel": "Nenhum erro durante a última sincronização"
    }
});