define([], function() {
    return {
        "TaxonomyPickerSuggestedTerms": "Termeni sugerați",
        "TaxonomyPickerNoTerm": "Nici un termen gasit",
        "TaxonomyPickerTermLocationPrefix": "In",
        "saveButtonLabel": "Inregistrare",
        "cancelButtonLabel": "Anulare",
        "selectTermLabel": "Selectați un termen...",
        "PeoplePickerSuggestion": "Sugestii",
        "PeoplePickerNoResults": "Nici un rezultat.",
        "PeoplePickerLoading": "Incarcare….",
        "EmptyPeoplePicker": "Vreti sa selectionati un utilizator",
        "takePicture": "Take a picture",
        "startVideo": "Begin capture",
        "stopVideo": "Stop capture",
        "removeButtonLabel": "Sterge",
        "NoMediaMessage": "Nu există suporturi de afisat",
        "NavHomeText": "Revenire la pagina de inceput",
        "FullscreenLabel": "Afișare în modul ecran complet",
        "AbortFullScreenLabel": "Părăsirea modului ecran complet",
        "ElementTypeColumnLabel": "Tip de element",
        "OperationColumnLabel": "Operatie",
        "AddLabel": "Adaugare",
        "UpdateLabel": "Actualizare",
        "DeleteLabel": "Eliminare",
        "UploadLabel": "Incarcare",
        "titleLabel": "Titlu",
        "IdColumnLabel": "ID",
        "PendingTransactionsLabel": "Tranzacții în așteptarea sincronizării",
        "TransactionErrorsLabel": "Eroare de sincronizare",
        "NoTransactionsLabel": "Nici o tranzactie in curs",
        "NoSyncErrorsLabel": "Nici o eroare în timpul ultimei sincronizări ",
        "clearSyncErrors": "Ștergeți lista"
    }
});