define([], function() {
    return {
        "TaxonomyPickerSuggestedTerms": "Предлагаемые термины",
        "TaxonomyPickerNoTerm": "Термины не найдены",
        "TaxonomyPickerTermLocationPrefix": "В",
        "saveButtonLabel": "Сохранить",
        "cancelButtonLabel": "Отменить",
        "selectTermLabel": "Выберите термин...",
        "PeoplePickerSuggestion": "Советы",
        "PeoplePickerNoResults": "Нет результатов.",
        "PeoplePickerLoading": "Загрузка…",
        "EmptyPeoplePicker": "Выберите, пожалуйста, оператора",
        "takePicture": "Сделать фото",
        "startVideo": "Начать запись",
        "stopVideo": "Закончить запись",
        "removeButtonLabel": "Удалить",
        "NoMediaMessage": "Нет данных для отображения",
        "NavHomeText": "Перейти на главную страницу",
        "FullscreenLabel": "Переключиться в полноэкранный режим",
        "AbortFullScreenLabel": "Выйти из полноэкранного режима",
        "ElementTypeColumnLabel": "Тип элемента",
        "OperationColumnLabel": "Операция",
        "AddLabel": "Добавить",
        "UpdateLabel": "Обновить",
        "DeleteLabel": "Удалить",
        "UploadLabel": "Загрузить",
        "titleLabel": "Название",
        "IdColumnLabel": "ID",
        "PendingTransactionsLabel": "Операция ожидает синхронизации",
        "TransactionErrorsLabel": "Ошибка синхронизации",
        "NoTransactionsLabel": "Выполняющиеся транзакции отсутствуют",
        "NoSyncErrorsLabel": "Ошибки синхронизации отсутствуют",
        "clearSyncErrors": "Очистить список"
    }
});