define([], function() {
    return {
        "TaxonomyPickerSuggestedTerms": "Predloženi termini",
        "TaxonomyPickerNoTerm": "Nije pronađen nijedan termin",
        "TaxonomyPickerTermLocationPrefix": "u",
        "saveButtonLabel": "Sačuvaj",
        "cancelButtonLabel": "Otkaži",
        "selectTermLabel": "Izaberite termin...",
        "PeoplePickerSuggestion": "Predlozi",
        "PeoplePickerNoResults": "Nema rezultata.",
        "PeoplePickerLoading": "Učitava se ...",
        "EmptyPeoplePicker": "Izaberite korisnika",
        "takePicture": "Take a picture",
        "startVideo": "Begin capture",
        "stopVideo": "Stop capture",
        "removeButtonLabel": "Obriši",
        "NoMediaMessage": "Nema medija za prikaz",
        "NavHomeText": "Idite na početnu stranicu",
        "FullscreenLabel": "Prikaži preko celog ekrana",
        "AbortFullScreenLabel": "Izlaz iz pregleda preko celog ekrana",
        "ElementTypeColumnLabel": "Tip elementa",
        "OperationColumnLabel": "Operacija",
        "AddLabel": "Dodaj",
        "UpdateLabel": "Ažuriraj",
        "DeleteLabel": "Obriši",
        "UploadLabel": "Učitaj",
        "titleLabel": "Naslov",
        "IdColumnLabel": "ID (identifikacija)",
        "PendingTransactionsLabel": "Transakcije koje čekaju sinhronizaciju",
        "TransactionErrorsLabel": "Greške u sinhronizaciji",
        "NoTransactionsLabel": "Nema tekućih transakcija",
        "NoSyncErrorsLabel": "Nema greške prilikom poslednje sinhronizacije"
    }
});